version: '3'

services:
    sio_nginx:
        build: ./nginx
        container_name: sio_nginx
        ports:
            - "80:80"
        volumes:
            - ${PHP_WEBROOT}:/var/www/${PROJECT_NAME}
        depends_on:
            - sio_php
            - sio_db
        networks:
            - backend-tier
    sio_php:
        build: ./php
        container_name: sio_php
        ports:
            - "9000:9000"
        volumes:
            - ${PHP_WEBROOT}:/var/www/${PROJECT_NAME}
        env_file: .env
        depends_on:
            - sio_db
        networks:
            - backend-tier
    sio_db:
        image: mysql
        container_name: sio_db
        ports:
            - "3306:3306"
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/dumps:/dumps
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: .env
        networks:
            - backend-tier

networks:
    backend-tier:
        driver: bridge
