name: PHPUnit Tests

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - develop
      - fix-14
    types:
      - push

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - name: Check pull_request Branch Name
        run: |
          PR_BRANCH=$GITHUB_REF
          echo "pull_request branch: $PR_BRANCH"
          if [[ "$PR_BRANCH" == *"/fix-14" ||  "$PR_BRANCH" == *"/master" ||  "$PR_BRANCH" == *"/develop" ]]; then
            echo "Excluded branch, skipping the workflow."
            exit 0
          fi
          echo "Not an excluded branch, continuing with the workflow."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker
        run: |
          cp docker/.env-dist docker/.env
          make build -C docker

      - name: Docker up
        run: |
          make up -C docker
          sleep 30

      - name: Install Composer
        run: docker exec -t sio_php bash -c 'composer install'


      - name: Create test environment
        run: |
          docker exec -t sio_db bash -c '${{ secrets.MYSQL_CONNECTION_STRING }} -e "SHOW DATABASES;"'
          docker exec -t sio_php bash -c 'composer run-script create-test-environment'

      - name: Run tests
        run: docker exec -t sio_php bash -c 'php vendor/bin/phpunit'

